### ISSUE TITLE
Error When Navigation Back

### ISSUE THREAD

**Issue by alek43** [utsmannn/osm-android-compose#1]
Haloo utsmann, i have try your lib, but i got some error, when i got back requested after load the maps the apps force closing.

**Comment by alek43** [comment]
java.lang.IllegalStateException: Check failed.
                                                                                                    	at androidx.compose.runtime.saveable.SaveableStateRegistryImpl.performSave(SaveableStateRegistry.kt:138)
                                                                                                    	at androidx.compose.runtime.saveable.SaveableStateHolderImpl$RegistryHolder.saveTo(SaveableStateHolder.kt:125)
                                                                                                    	at androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1$invoke$$inlined$onDispose$1.dispose(Effects.kt:484)
                                                                                                    	at androidx.compose.runtime.DisposableEffectImpl.onForgotten(Effects.kt:85)
